### ISSUE TITLE
Db table schema

### ISSUE THREAD

**Issue by Abishevs** [NTI-Gymnasiet-Nacka/projekt-1-tital00s-grupp-erik#5]
Given requirements by #2
With SQLAlchemy
And authors column as an : or ; seperated string. 

Others add as an appropriate sql type. 
 
Db fields in table:

- id
- type
- #2 fields
- created_at
- updated_at

Created_at is also used as access date field (but should be transformed to the given format when used)

**Comment by LeoAllStar** [comment]
Finished
